config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'signup' => 'users#new'

 # get 'the_first_pages/home'
  
  get 'home'=> 'the_first_pages#home'

  get 'the_first_pages/help'
  
  # get 'the_first_pages/about'
  get 'about'=> 'the_first_pages#about'

  get 'for_first_heroku/ps_home'
  
  # for sessions
  get     'login'=> 'sessions#new'
  post    'login'=> 'sessions#create'
  delete  'logout'=> 'sessions#destroy'
  
  
  root 'the_first_pages#home'
  
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 18}
  VALID_EMAIL_REGEX = /\A([a-z]|[1-9]){1,45}\.?([a-z]|[1-9]){1,45}@([a-z]|[1-9]){1,45}\.[a-z]{2,9}\z/i
  validates :email, presence: true, length: {maximum: 27}, 
        format: {with: VALID_EMAIL_REGEX},
        uniqueness: { case_sensitive: false }
  validates :sex, length: {maximum: 9}
  has_secure_password
  validates :password, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/for_first_heroku_controller.rb
class ForFirstHerokuController < ApplicationController
  def ps_home
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #make enter user
    else
      #error message
      flash.now[:danger] = "неправильная комбинация пароль/логин"
      render 'new'
    end
  end
  def destroy
  end
end

app/controllers/the_first_pages_controller.rb
class TheFirstPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params) 
    if @user.save 
      flash[:success] = "регистрация успешна - молодец, млин... многого добился :)"
      redirect_to @user
    # обработка сохранения 
    else 
    render 'new' 
    end 
  end 
  private
  def user_params
    params.require(:user).permit(
      :name, 
      :email, 
      :sex, 
      :password, 
      :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "LESSON 3"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end 
end

app/helpers/for_first_heroku_helper.rb
module ForFirstHerokuHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/the_first_pages_helper.rb
module TheFirstPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #for gravatar
  def gravatar_for(user)
    pamm = Digest::MD5::hexdigest(@user.email.downcase)
    if pamm == "654989e1ae53154737e15968ad3dd5e0"
      gravatar_id = Digest::MD5::hexdigest("nosnana.web@gmail.com")
  else
      gravatar_id = pamm
    end
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: @user.name, class: "gravatar")
  end
  def usrs_sex
    the_sx = "оно"
    if @user.sex == "man"
      the_sx = "мужик"
    end
    return the_sx
  end
  
  
end

app/views/for_first_heroku/ps_home.html.erb
<% provide(:ttl, "проверочка в титле")%>

<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:ttl)) %></title>
    <%= csrf_meta_tags %>

   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  </head>
  
  <body>
    <%= flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert-#{message_type}") %>
    <% end %>
    
    <%= render 'sha/navbar' %>
    <%= yield %>
    
    
    
<footer class="footer">
        <p>&copy; 2017 ноябрь - декабрь, впрочем, какое это имеет значение :(</p>
  <div class:="the_my_class_for_footer">
        <p>some text: Lorem ipsum dolor sit amet, 
consectetur adipiscing elit. Pellentesque luctus volutpat ipsum, 
vitae eleifend libero viverra a. Nullam gravida massa et nibh dictum venenatis. 
Vivamus interdum auctor lacus, vitae ornare nisl accumsan ut. 
Aliquam a erat lorem. Sed ultrices, erat id fringilla tincidunt, 
leo mi rutrum risus, vel laoreet erat dolor at velit. </p> 
  </div>
</footer>

<div class="col-lg-6">
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/sha/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">БРЭНДДД</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">А ЭТО МОЯ? НЕТ! <span class="sr-only">(current)</span></a></li>
        <li><a href="#">ЭТО ССЫЛКА</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          
          
          <!-- <a href="#">ДОМАШНЯЯ СТРАНИЦА</a> -->
          <%= link_to "моя ДОМАшНяя СТРАНИцА", home_path %>
          
          
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "УВАХОД", login_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/the_first_pages/about.html.erb
<% provide(:ttl, "this is ABOUT-PAGE")%>

<div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Привет... чето ниче найти не могу...</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
          </div>
          <div class="row">
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
          </div>
        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>

    </div><!--/.container-->

app/views/the_first_pages/help.html.erb
<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="#">About</a></li>
            <li role="presentation"><a href="#">Contact</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Project name</h3>
      </div>

      <div class="jumbotron">
        <h1>Jumbotron heading</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <footer class="footer">
        <p>&copy; 2016 Company, Inc.</p>
      </footer>

    </div> <!-- /container -->
  
  <% provide(:ttl, "this is HELP-PAGE")%>

app/views/the_first_pages/home.html.erb
<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active">
              
              <!-- <a href="#">Home</a> -->
              <%= link_to "home", home_path %>
              </li>
            <li role="presentation">
              
              
            <!--   <a href="#">About</a>  -->
            <%= link_to "О Проекте", about_path %>
              
              
              </li>
            <li role="presentation"><a href="#">Contact</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Учебно-тренировочная площадка</h3>
      </div>

      <div class="jumbotron">
        <h1>Учебно-тренировочный проект</h1>
        <p class="lead">Используем Bootstrap (http://getbootstrap.com) для стилей</p>
        <p>
          
          <!-- <a class="btn btn-lg btn-success" href="#" role="button">Регистрация</a> -->
          <%= link_to "РЕГИСТРАЦИЯ", signup_path, class: "btn btn-lg btn-success" %>
          
          </p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Бутстрап</h4>
          <p>Классный фреймворк стилей в стиле твитера :) тут некоторые ссылки, чтобы не забыть:
          <br><b> http://mybootstrap.ru</b> - русский сайт - всё предельно понятно
           <br><b> https://tokar.ua/read/7557</b> - украинский сайт - конкретно простые и понятные уроки по бутстрап
            <br><b> https://getbootstrap.com</b> - наверняка это офсайт :)
          
          </p>
           </div>
           
           <div class="col-lg-6">

          <h4>Регулярные выражения</h4>
          <p>Тут классный сервис: <b>http://rubular.com</b> - специально для рубина... 
          <br>Вот, к примеру, это я составил для емэйлов... 
          (  /\A([a-z]|[1-9]){1,45}\.?([a-z]|[1-9]){1,45}@([a-z]|[1-9]){1,45}\.[a-z]{2,9}\z/i  )
          но оно слишком длинное... зато мое :) <br>
          а вот то, что сейчас: (  /\A[\w+\-]+@[a-z\d-]+\.[a-z]+\z/i  ) - но оно не будет работать 
          если есть точка в имени - к примеру nosnana.web... но это пока и не важно в учебном проекте.
          <br> тем не менее, вот, что можно сделать: (  /\A([\w+\-]+)\.?([\w+\-]+)@[a-z\d-]+\.[a-z]+\z/i  )
          и воно працуе...
          
          </p>
        </div>
        
        <div class="col-lg-6">

          <h4>Аватар в профиле</h4>
          <p>Используем сервис: <b>http://gravatar.com</b> hhh 
          <br>ghghhghghghghg <br>
          ghghghghghghgh
          <br> hghghghghgh
          
          </p>
        </div>
        
      </div>

    </div> <!-- /container -->
  
  
  <% provide(:ttl, "this is HOME")%>

app/views/users/new.html.erb
<% provide(:ttl, "THE PAGE OF REGISTRATION :) FUCKing People!") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <h1>РЕГИСТРАЦИЯ</h1>
    
     <%= form_for(@user) do |f| %>
    
    <p><%= f.label :name, "Ваше имя" %></p>
    <p><%= f.text_field :name %></p>
    
    <p><%= f.label :email, "Введите свой емэйл - он будет в роли логина" %></p>
    <p><%= f.email_field :email %></p>
    
    <p><%= f.label :sex, "Каков ваш пол" %></p>
    <p><%= f.text_field :sex %></p>
    
    <p><%= f.label :password, "Придумайте пароль" %></p>
    <p><%= f.password_field :password %></p>
    
    <p><%= f.label :password_confirmation, "Подтвердите пароль" %></p>
    <p><%= f.password_field :password_confirmation %></p>
    
    <p><%= f.submit "Создать аккаунт", class: "btn btn-primary" %></p>
    <% end %>
  </div>    
</div>

app/views/users/show.html.erb
<% provide(:ttl, "PRIVAT INFO by " + @user.name)%>

<h3>Страница пользователя <b><%= @user.name %></b></h3>

<div class="row">
  <aside class="col-md-4">
   <section class="user_info">
     <div class="gravatar"><%= gravatar_for @user %></div>
<p>Имя: <%= @user.name %></p>
<p>Мыло: <%= @user.email %> </p>
<p>Пол: <%= usrs_sex %> </p>
<p>Паровоза хэш: <%= @user.password_digest %> </p>
     
   </section> 
    
  </aside>
  
  
</div>


  
  